#!/usr/bin/env bash
# creates a pid file, displays different messages with different signals
clean()
{
        rm -f /var/run/myscript.pid
	echo "I hate the kill command"
                exit
}
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; clean' SIGTERM
echo $$ > /var/run/myscript.pid
while true; do
echo "To infinity and beyond"
sleep 2
	done
