#!/usr/bin/env bash
# displays time in hours and minutes
hr=0
while [ $hr -le 12 ]; do
if [ $hr -eq 0 ]; then
echo "Hour: 0"
else
echo "Hour: $hr"
fi
min=1
while [ $min -le 59 ]; do
	echo "$min"
min=$((min + 1))
	done
hr=$((hr + 1))
	done
